const arena=document.getElementById('arena'),player=document.getElementById('player'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),message=document.getElementById('message'),start=document.getElementById('start'),jumpBtn=document.getElementById('jump');
let playing=false,jumping=false,score=0,best=Number(localStorage.getItem('oio-dash-best')||0),speed=5,spawnTimer=0,last=0,obstacles=[];
bestEl.textContent=best;
function jump(){if(!playing||jumping)return;jumping=true;player.animate([{transform:'translateY(0)'},{transform:'translateY(-105px)'},{transform:'translateY(0)'}],{duration:520,easing:'cubic-bezier(.2,.8,.3,1)'}).finished.finally(()=>jumping=false)}
function startGame(){obstacles.forEach(o=>o.remove());obstacles=[];score=0;speed=5;spawnTimer=0;scoreEl.textContent=0;message.classList.add('hidden');playing=true;last=performance.now();requestAnimationFrame(loop)}
function spawn(){const o=document.createElement('div');o.className='obstacle';o.style.height=(35+Math.random()*55)+'px';o.style.right='-40px';arena.appendChild(o);obstacles.push(o)}
function hit(a,b){const A=a.getBoundingClientRect(),B=b.getBoundingClientRect();return A.left<B.right-8&&A.right>B.left+8&&A.top<B.bottom-8&&A.bottom>B.top+8}
function gameOver(){playing=false;message.classList.remove('hidden');message.querySelector('h1').textContent='GAME OVER';message.querySelector('p').textContent=`Você fez ${Math.floor(score)} pontos`;start.textContent='JOGAR DE NOVO';if(score>best){best=Math.floor(score);localStorage.setItem('oio-dash-best',best);bestEl.textContent=best}}
function loop(t){if(!playing)return;const dt=Math.min(32,t-last);last=t;score+=dt*.01;scoreEl.textContent=Math.floor(score);speed=5+score/70;spawnTimer+=dt;if(spawnTimer>Math.max(600,1150-score*2)){spawn();spawnTimer=0}
for(let i=obstacles.length-1;i>=0;i--){const o=obstacles[i],x=parseFloat(o.style.right);o.style.right=(x+speed*dt/16)+'px';if(hit(player,o)&&!jumping){gameOver();return}if(x>arena.clientWidth+60){o.remove();obstacles.splice(i,1)}}requestAnimationFrame(loop)}
start.addEventListener('click',startGame);jumpBtn.addEventListener('pointerdown',e=>{e.preventDefault();jump()});arena.addEventListener('pointerdown',e=>{if(e.target!==start)jump()});document.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();jump()}if(e.code==='Enter'&&!playing)startGame()});
